!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
!C     Genetic Subroutines to handle Sparse Matrix generated by DVR           C
!C          Jacobi Diagonization using dynamical allocation                   C
!CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

!ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
 subroutine HOSBINIT_XYZ(X_BLK, X_MAK, X_NDK, X_H1IN, X_RES, X_HOSB)
      integer, intent(IN) :: X_BLK, X_MAK, X_NDK 
      double precision,intent(IN):: X_H1IN(X_MAK,X_MAK)  
      double precision,intent(IN):: X_RES(X_NDK,X_MAK,X_BLK)
      double precision,intent(INOUT):: X_HOSB(X_NDK,X_MAK,X_MAK,X_BLK)
      
      integer :: I, J, K    

      do I = 1, X_BLK
         do J=1, X_MAK
            do K=1, X_MAK
               X_HOSB(1:X_NDK,K,J,I) = X_H1IN(K,J)
            end do
         end do
      end do
             
      do J = 1, X_BLK
         do K = 1, X_MAK
            X_HOSB(1:X_NDK,K,K,J) = X_HOSB(1:X_NDK,K,K,J) + X_RES(1:X_NDK,K,J)
         end do
      end do

 end subroutine
!ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
 subroutine HOSBINIT_XYZ_CX(X_BLK, X_MAK, X_NDK, X_H1IN, X_RES, X_HOSB)
      integer, intent(IN) :: X_BLK, X_MAK, X_NDK 
      double complex,intent(IN):: X_H1IN(X_MAK,X_MAK)  
      double precision,intent(IN):: X_RES(X_NDK,X_MAK,X_BLK)
      double complex,intent(INOUT):: X_HOSB(X_NDK,X_MAK,X_MAK,X_BLK)      

      integer :: I, J, K    

      do I = 1, X_BLK
         do J=1, X_MAK
            do K=1, X_MAK
               X_HOSB(1:X_NDK,K,J,I) = X_H1IN(K,J)
            end do
         end do
      end do
             
      do J = 1, X_BLK
         do K = 1, X_MAK
            X_HOSB(1:X_NDK,K,K,J) = X_HOSB(1:X_NDK,K,K,J) + X_RES(1:X_NDK,K,J)
         end do
      end do

 end subroutine
!ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
